# Theme
#theme: "just-the-docs"
baseurl: "/"
remote_theme: pmarsceill/just-the-docs

# Search
search_enabled: true
search_tokenizer_separator: /[\s/]+/

# Aux links for the upper right navigation
aux_links:
    "APi Broker on GitHub":
      - "//github.com/api-broker/api-borker"

heading_anchors: true

footer_content: "Copyright &copy; 2017-2019 API Broker. Distributed by an <a href=\"https://opensource.org/licenses/MIT\">MIT license.</a>"